CREATE TABLE IF NOT EXISTS rag_knowledge (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  titulo     VARCHAR(255)  NOT NULL,
  contenido  TEXT          NOT NULL,
  categoria  VARCHAR(100)  NOT NULL DEFAULT 'General',
  created_at TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
